# Generated by Django 5.0.3 on 2024-04-03 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.IntegerField()),
                ("birth_date", models.DateTimeField()),
                ("year_of_driving_experience", models.IntegerField()),
                ("starting_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("liscence_plate", models.SlugField(max_length=100)),
                ("time_of_departure", models.DateTimeField()),
                ("max_seats", models.IntegerField()),
                ("starting_station", models.CharField(max_length=100)),
                ("final_station", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON PLATFORM", "On platform"),
                            ("ARRIVING", "Arriving"),
                            ("LEAVING", "Leaving"),
                            ("LEFT", "Left"),
                        ],
                        max_length=11,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("seat_number", models.IntegerField(unique=True)),
                ("passenger_fullname", models.CharField(max_length=100)),
                (
                    "bus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bus",
                    ),
                ),
            ],
        ),
    ]
