# Generated by Django 5.0.3 on 2024-04-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name_plural": "Buses"},
        ),
        migrations.AlterField(
            model_name="driver",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
    ]
