# Generated by Django 5.0.3 on 2024-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_bus_options_alter_driver_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatreservation",
            name="seat_number",
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name="seatreservation",
            constraint=models.UniqueConstraint(
                fields=("bus", "seat_number"), name="unique_seat_per_bus"
            ),
        ),
    ]
